src/Datetime.cpp

This fixes https://github.com/GothenburgBitFactory/timewarrior/issues/112. Timewarrior requires dates to be in the past.

TI-#112: Add timeRelative flag to initialization of day names

---

test/CMakeLists.txt

This policy is no longer necessary because CMake issue #16062, which caused incorrect warnings to be shown, has been resolved in 3.11.0.

Do not set CMP0037 on CMake 3.11.0 and above

---

src/ip.cpp
test/datetime.t.cpp

* isIPv4Address() didn't correctly set the port to zero and causes test fails
* the number of tests in datatime.t needs update

Fix isIPv4Address() and datetime test

---

CMakeLists.txt
cmake.h.in
src/format.cpp

Hi!
When I compile taskshell and friends on OpenBSD I get the following warnings:
```liblibshared.a(format.cpp.o): In function `formatTime(long long)':```
```....../taskshell/src/libshared/src/format.cpp:(.text+0x6840): warning: strcpy() is almost always misused, please use strlcpy()```
```liblibshared.a(format.cpp.o): In function `formatBytes(unsigned long)':
....../taskshell/src/libshared/src/format.cpp:(.text+0x6488): warning: sprintf() is often misused, please use snprintf()```
```[100%] Built target tasksh_executable```
Fixing `sprintf()` is a no-brainer, but `strlcpy()` requires that we check that it exists before use. To get `strlcpy()` into task warrior and the other tools, the `HAVE_STRLCPY` needs to be declared, tentatively like in this patch.

Use safe functions

---

src/Datetime.cpp
test/datetime.t.cpp

When true, it puts months before and including current month into next year
When false, it puts months always into current year
This should fix https://github.com/GothenburgBitFactory/timewarrior/issues/228

Make initializeMonth adhere to timeRelative flag

---

src/Datetime.cpp
test/datetime.t.cpp

Fixes an error in the conversion of weekday names into a date in respect of Timewarrior's need to get a date in the past.
Fixes https://github.com/GothenburgBitFactory/timewarrior/issues/194

Fix parsing of weekday names to dates

---

src/FS.cpp
test/fs.t.cpp

File::copy would return true even if it was unable to actually copy the
data from the source file to the destination file.
This function also does not need a separate access check since ifstream will
already set the fail bit if something went wrong with the open.
GothenburgBitFactory/timewarrior#155

File::copy () should return false on I/O errors

---

src/shared.cpp

In timewarrior, I had a broken link to an extension. The result was that
the report would fail without output (but a -1 return code).
This change allows some more context to be printed about why the run
failed (file missing, not executable, etc..)
Related to GothenburgBitFactory/timewarrior#367
Signed-off-by: Shaun Ruffell <sruffell@sruffell.net>

execute: Write an error to stderr if execution fails

---

src/FS.cpp

While testing my changes in https://github.com/GothenburgBitFactory/taskwarrior/pull/2316 , I noticed that taskwarrior failed to create the proper directory if its parent directory didn't exist.
All comments, alternatives and improvement suggestions welcome.

support recursive creation of directories

---

CMakeLists.txt
ChangeLog
cmake/CXXSniffer.cmake

C++17 is partially available since GCC5 (released in 2015) and default
since GCC11 (released in April 2021). TaskWarrior requires C++17 as
well. However TimeWarrior documentation says C++14 is enough.
CXX_STANDARD_REQUIRED is not set so it should try to fall back to whatever
standard is available.
Also requires bumping minimum cmake version to 3.1 (released in 2018).

Switch to C++17.

---

src/Datetime.cpp

make the comments accurate after changes, cf issue #2519

Update end-dates in comments corresponding to PR #2522

---

src/Table.cpp
src/format.cpp

Faster.
Found with performance-faster-string-find

clang-tidy: use single character '' for find

---

test/json.t.cpp
test/sax_test.cpp

Found with modernize-use-override

clang-tidy: add missing override

---

src/Lexer.cpp
src/PEG.cpp
src/shared.cpp
test/shared.t.cpp

Found with readability-redundant-string-init

clang-tidy: remove pointless string init

---

src/Configuration.cpp
src/Configuration.h

In order to obtain configuration values overwritten for the current context, a convenience function has been added to Configuration.h

Added convenience function to obtain configuration from active context.

---

src/RX.h

Found with readability-inconsistent-declaration-parameter-name

clang-tidy: fix inconsistent declarations

---

src/Composite.cpp
src/Packrat.cpp
src/Packrat.h
src/Tree.cpp
src/Tree.h

Some of them it does not fix automatically.

clang-tidy: run through all performance checks

---

src/Configuration.cpp

Configuration options that contain environment variables are now parsed.
This allows for example setting the path of the TLS keys for
synchronization with the taskd server different on each machine.

Parse env variables for configuration options

---

src/Datetime.cpp

The parse_time method is enforced only if standaloneTimeEnabled is set
to true, because it's rather liberal - in particular, many four digit
numbers can be interpreted as 4 digit time (i.e 1020 standing for
10:20am).
It only follows that parse_time_off, which identifies offsetted time
tokens of the form hh[mm]±hh[mm] (which can match a token representing a
range, i.e. '1020-1024') should also respect the same flag.
Related to https://github.com/GothenburgBitFactory/taskwarrior/issues/2639.

Datetime: parse_time_off should respect standaloneTimeEnabled

---

src/Datetime.cpp
test/dates.t.cpp

This partially resolves #49, by making sure that `soww` refers to the current work week. Also adjusts the tests accordingly.

Fix the computation for the soww named date

---

src/FS.cpp

F_FULLFSYNC is not supported on all file systems (i.e. Google Drive) and on
Darwin we do not want to limit timewarrior / taskwarriors databases to only
those that support the F_FULLFSYNC operation.
For those filesystem, we will now fallback to the fsync call.
Signed-off-by: Shaun Ruffell <sruffell@sruffell.net>

FS: Do not require F_FULLFSYNC support on DARWIN

---

src/Datetime.cpp

Found with modernize-return-braced-init-list

clang-tidy: use braced init return

---

src/Datetime.cpp
src/Datetime.h
src/Duration.cpp
src/Duration.h
src/Lexer.cpp
src/Lexer.h
src/format.cpp
src/format.h
src/utf8.cpp
src/utf8.h

Found with readability-const-return-type

clang-tidy: avoid double const

---

src/Configuration.cpp
src/FS.cpp
src/Tree.cpp
src/shared.cpp

clang-tidy doesn't convert these for some reason.

manual conversions to empty()

---

src/Packrat.cpp
src/Packrat.h
test/external.t.cpp

clang-tidy found these but was not able to automatically fix them.

manual const ref conversions

---

src/Color.cpp
src/Configuration.cpp
src/Datetime.cpp
src/Duration.cpp
src/FS.cpp
src/Log.cpp
src/PEG.cpp
src/Packrat.cpp
src/RX.cpp
src/Tree.cpp
src/shared.cpp
test/negative.t.cpp
test/peg.t.cpp
test/plus.t.cpp
test/positive.t.cpp
test/question.t.cpp
test/star.t.cpp

Found with readability-container-size-empty

clang-tidy: replace size comparisons with empty

---

src/JSON.h

GCC 13 (as usual for new compiler releases) shuffles around some internal includes so some are no longer transitively included.
See https://gnu.org/software/gcc/gcc-13/porting_to.html.
Bug: https://bugs.gentoo.org/895122

JSON: Fix build with GCC 13

---

src/Datetime.cpp
test/dates.t.cpp

The calculation of the _end of previous work week_ (eopww) fails if the current day is a Saturday.
The algorithm ([Datetime.cpp:2059](https://github.com/GothenburgBitFactory/libshared/blob/ee050a2cc68c46e8748113246b26feb0ad9f34c5/src/Datetime.cpp#L2059-L2063)) subtracts the current weekday (with Sunday = 0) plus one modulo 7 from the current day of month.
When the current day is a Saturday, this results in a subtraction of 0, i.e. the current day remains unchanged, while it should be the previous Saturday.
Dropping the modulo fixes the issue.

Fix calculation of 'end of previous work week'

---

.github/workflows/cmake.yml
docker-compose.yml
test/docker/task.dockerfile
test/docker/timew.dockerfile

Build both, Taskwarrior and Timewarrior, at 'stable' and 'develop' with the current version of libshared.

Add integration tests for Timewarrior and Taskwarrior

---

.github/workflows/cmake.yml
test/docker/task.dockerfile

A couple fixes to get the test runner working again:
- Github has retired "docker-compose" (ie v1) and now requires to be invoked as "docker compose".  See url to a discussion in the commit message.
- Also there were some recent changes to Taskwarrior cmake rules whilst making C++ tests run with a single executable, which now requires a trivial change in the docker file.
After these fixes, the tests work again.

Fix test runs after recent gh/docker/cmake changes

---

src/Datetime.cpp
test/datetime.t.cpp

This PR implements the ISO8601 algorithm for `Datetime::weekstart == 1` while retaining existing behavior for `Datetime::weekstart == 0`.
There are some issues with the existing week number parsing:
- Weeks start on Sunday if specified using week numbers like `2024-W31`.
- These weeks do not correspond to e.g. `sow`, `sonw`, which are Monday-based.
- Neither do these weeks correspond to timewarrior hints like `:week`, `:lastweek`.
- The weekdays in such a string (`5` in `2013-W49-5`) use 0-6 Sunday-Monday syntax rather than 1-7 Monday-Sunday as specified in ISO8601
- The week numbers for certain year transitions do not correspond to ISO weeks.
- Value of `Datetime::weekstart` set in libshared does not change any of this, whether set to 0 or 1.
For example `2013-W49` is a frequently tested …

Make week number parsing ISO8601 compliant for weekstart=1

---

src/Datetime.cpp

When working on GothenburgBitFactory/taskwarrior#3623, after modifying the code to pass the user-configured `rc.weekstart` down into `Datetime::weekstart`, it was discovered that the returned week number from `Datetime::week()` was one more than it should be when `weekstart=0` (but not `weekstart=1`).  The code was doing:
```
char weekStr[3];
struct tm* t = localtime (&_date);
strftime (weekStr, sizeof (weekStr), "%U", t);
int weekNumber = strtol (weekStr, NULL, 10);
if (weekstart == 0)
weekNumber += 1; // <-- HERE
```
This increment was never activated before, because `Datetime::weekstart` was initialized to 1 in the library, and never altered by TW.  Now that it can be set using configuration (in forthcoming patch), there was breakage seen with `weekstart=0` (but not `weekstart=1`). …

Fix week number from Datetime::week() when weekstart=0

---

src/Datetime.cpp
src/Datetime.h

Expose them so they can be used in other places.
See https://github.com/GothenburgBitFactory/taskwarrior/pull/3651 for example of usage.

Add defines for the values that are allowed for epoch timestamps

---

src/Color.cpp
test/color.t.cpp

There is no reason that bold cannot work in 256 color space. Perhaps initially this was disabled due to old terminals not supporting bold and 256 control codes. But in 2024 there is no reason to disable bold.
This PR fixes this and allows users to use bold in themes no matter whether 256 color or 16 color space is used.

feat: add bold color with 256 color space

---

.github/workflows/cmake.yml

GitHub is removing the `macOS 12` runner image by 2024-12-03
See https://github.com/actions/runner-images/issues/10721

Remove 'macOS 12' GitHub runner

---

src/Color.cpp
src/Color.h
test/color.t.cpp

Here's a suggestion for 24-bit color ("truecolor") support:
* Keep the original structure of stuffing all color information into a single integer.
* But use a 64 bit int instead.
* If 24-bit color: store the background color in the upper half.
resolves #3

Add 24bit color support

---

src/Datetime.cpp
src/Datetime.h

This allows larger deltas, as `int` is only 32 bits. Even on platforms where time_t is 32 bits, using `int64_t` is not worse than using `int`.

Use 64-bit delta for Datetime +/- operators

---

src/JSON.cpp
test/json.t.cpp

This fixes a bug where such an input produced a string with a spurious trailing NUL character. This also adds tests for embedded NULs, but those already passed. Fixes #95.

Handle `\` at end of string in JSON::decode.

---

src/utf8.cpp
test/shared.t.cpp

Values in a `std::string` can contain NUL characters, and these should not necessarily indicate the end of the string.
Fixes #93.

extractLine: Handle embedded NULs correctly

---

src/Datetime.h

The previous move of `Datetime::timegm()` into libshared (from Taskwarrior) in PR #99 caused a significant performance regression in Timewarrior because a slow fallback method was used due to `-DHAVE_TIMEGM` not being picked up from cmake.
That fallback calls `tzset()` for every `timegm()` call, which is done twice for every interval in the Timewarrior data, and involves file I/O with `/etc/localtime`.  These calls can number in the tens of thousands even for simple operations, depending on time db size.
This patch includes `cmake.h` so the `HAVE_TIMEGM` define can be picked up and we'll defer to the libc implementation of `timegm()`, which is much faster (it does not do `tzset()`).
Windows may still be affected by the slowness, it may not have `timegm()`, but it will continue to work …

Fix Datetime.{h,cpp} to include cmake.h for HAVE_TIMEGM define
